### ISSUE TITLE
Unhandled Promise Rejection when I enter project name

### ISSUE THREAD

**Issue by emadabdulrahim** [intuit/design-systems-cli#106]
Followed the instructions and after using the command 
```sh
npm init @design-systems
```

When I enter a name  I get this error

![image](https://user-images.githubusercontent.com/7950797/73116437-25c31500-3eeb-11ea-87cd-f58f64577013.png)

Any idea how to fix?

**Comment by hipstersmoothie** [comment]
:rocket: Issue was released in v1.2.3 :rocket:

**Comment by hipstersmoothie** [comment]
Try now @emadabdulrahim 🚀
