### ISSUE TITLE
`create system --list-templates` broken

### ISSUE THREAD

**Issue by hipstersmoothie** [intuit/design-systems-cli#109]

**Comment by edgarsherman** [comment]
Is this still an issue?  I'm not able to reproduce.

![testingds – package json 2020-10-08 17-22-23](https://user-images.githubusercontent.com/24437339/95523130-14dc0600-098b-11eb-8e22-034597af173d.png)

**Comment by hipstersmoothie** [comment]
oh nice it work! Thanks for checking
