### ISSUE TITLE
passing command line options to 'ds lint' ex. --max-warnings 

### ISSUE THREAD

**Issue by keviny22** [intuit/design-systems-cli#200]
i don't see a way to pass `--max-warnings` to `ds lint` 

Is this possible?

Are you willing to accept open contribution to this feature?  If yes, should it be open or opinionated?

ex.

`ds lint --max-warnings 9`

or

`ds lint --options max-warnings=9`

**Comment by hipstersmoothie** [comment]
Open to PRs! `ds lint --max-warnings 9` is the way I'd do it.

**Comment by athityakumar** [comment]
@hipstersmoothie  - If @keviny22 isn't already working on this, I'd love to take it up! 😃

**Comment by hipstersmoothie** [comment]
Go for it?
