### ISSUE TITLE
Custom config for Playroom

### ISSUE THREAD

**Issue by orther** [intuit/design-systems-cli#248]
**Is your feature request related to a problem? Please describe.**

I need to wrap my components in a ThemeProvider container for them to be styled correctly. When I use Playroom my components aren't styled because I can't setup Playroom to use my ThemeProvider.
frameComponent working because Playroom isn't configured to use

**Describe the solution you'd like**

I'd like to be able to configure Playroom at the system / monorepo level when using `@ds-cli` to allow me to set a custom `frameComponent`.

**Comment by orther** [comment]
I'd be happy to make a PR for this functionality based on how custom configs work for other plugins (i.e. Storybook) if that makes sense.

**Comment by hipstersmoothie** [comment]
I'd be happy to accept that contribution! You're right, this is an oversight. We should def expose a way to customize playroom.

**Comment by orther** [comment]
@hipstersmoothie I'm new to working on monorepos and was curious about how you go about developing and testing ds-cli locally.

I was able to get things working well enough (PRs for playroom incoming) using [yalk](https://github.com/whitecolor/yalc) but I'm having to manually edit my package.json each time I need to run `yarn clean && yarn` and then before I run `yarn build`.

Any advice is appreciated!

**Comment by orther** [comment]
It looks like I may have been over complicating things by using yalc. I seem to be having good luck simply using `yarn workspace @design-systems/playroom link` in the root of ds-cli monorepo and doing `yarn link "@design-systems/playroom"` in root of integration-ds (local test project).

**Comment by hipstersmoothie** [comment]
The yarn link method should work as well. But if changing things in multiple packages you would also have to link those.

**Comment by orther** [comment]
Using the direct path to the bin file (and `yarn start`) is much simpler, better. Thanks!

**Comment by orther** [comment]
This was addressed with #251 (closing issue)
