### ISSUE TITLE
Size Private NPM repos

### ISSUE THREAD

**Issue by hainessss** [intuit/design-systems-cli#249]
Hello, 

I have a my repositories under my private NPM account.  I do not understand how to authorize the `size` command to have access to them. I have an .npmrc file with an auth token, but I believe the temp directory that is getting created to do the size calculation is outside of the project workspace? So the question is how do I allow `size` access to these private packages.  

I get this error: Error: Couldn't find package "@myscope/package@^0.0.10" required by xyz.

**To Reproduce**

Run `ds size` on a repository that has private modules. 

**Expected behavior**

Should be aware of my .npmrc or provide other method to pass authentication token. 

Thanks in advance for the help.

**Comment by hipstersmoothie** [comment]
For the `size` command you get set the registry it installs from in your `ds.config.json`

```json
{
  "size": {
    "registry": "https://your-registry.com"
  }
}
```

You could also use the flag that's available on the `size` command but it's probably better to set in the config.

**Comment by hipstersmoothie** [comment]
Please let me know if the fixes the issue

**Comment by hainessss** [comment]
I am not sure this fixes it. Because to access a npm private repo, you'd need to pass an authentication token.  So like:
```
{
  "size": {
    "registry": "https://registry.npmjs.org/:_authToken={token}"
  }
}
```
And the config does not work with a value like this.

**Comment by hipstersmoothie** [comment]
A PR may be need then to make this work. 

Here is the relevant code where we install from the registry

https://github.com/intuit/design-systems-cli/blob/9733116a4878b5b61cad39f5551c3700c9b11347/plugins/size/src/utils/WebpackUtils.ts#L179

Maybe we just need to copy the .npmrc into the temp directory? This would remove the need for the --registry flag at all, since this is probably in the npmrc

**Comment by hainessss** [comment]
Yeah I think that would make a lot of sense.

**Comment by hipstersmoothie** [comment]
Would you be interested in making the PR for this?

**Comment by hainessss** [comment]
I'll give it a whirl.

**Comment by hipstersmoothie** [comment]
dev setup is mainly:

```sh
# install deps
yarn
# Start build watch
yarn start
# In you project access the cli 
../design-systems-cli/packages/cli/bin/ds.js size
```

**Comment by hainessss** [comment]
#255  Fixes!
