### ISSUE TITLE
Playroom snippets aren't built starting at v1.7.0

### ISSUE THREAD

**Issue by orther** [intuit/design-systems-cli#252]
**Describe the bug**

No snippets are loaded in Playroom.

I believe this is due to snippet files not being built in the build step after PR #219 (this line specifically: https://github.com/intuit/design-systems-cli/commit/c7b6cb72f052faf5d8441a040e9b419d50769dd0#diff-bc07f02d36ef2d7ade1a2f1ee1935aa6R13)

**To Reproduce**

In a project updated to `ds-cli` version >=1.7.0 with at least one component snippet:

1. Clean dist dirs: `yarn clean --no-modules`
2. Build components: `yarn build`
3. Run playroom: `yarn playroom`
4. Notice that there aren't any snippets available

**Expected behavior**

Snippets are loaded and available in Playroom.

To get snippets working:

1. Manually edit the `node_modules/@design-systems/build/dist/command.js` file to _not_ ignore the snippet files:
	```js
    // ...
	export const defaults = {
	  watch: false,
	  inputDirectory: 'src',
	  outputDirectory: 'dist',
	  cssMain: 'main.css',
	  ignore: [
	    '**/*.+(md|mdx)',
	    '**/__tests__/**',
	    '**/__snapshots__/**',
	    // '**/*.+(stories|test|snippet).*'
	    '**/*.+(stories|test).*' // <~~ I remove `|snippet`
	  ]
	};
    // ...
	```
2. Build components: `yarn build`
3. Run playroom: `yarn playroom`
4. Snippets are now available

**Screenshots**

For reference this is what the Playroom UI looks like with and withOUT snippets.

| Playroom withOUT snippets | Playroom WITH snippets |
| -- | -- |
| ![image](https://user-images.githubusercontent.com/126236/82261266-93b89f80-9913-11ea-81e4-835f7a81fd23.png) | ![image](https://user-images.githubusercontent.com/126236/82261352-b1860480-9913-11ea-9ee1-365657a156da.png) |

**Desktop (please complete the following information):**

- OS: macOS 10.15.4
- Browser Chrome
- Version 1.7.0

**Additional context**

For reference here is the `ColorSwatch.snippet.tsx` in my `ColorSwatch` component that I'm testing with:
   ```js
   // File: ./components/ColorSwatch/src/ColorSwatch.snippet.tsx
   import React from 'react';
   import { ColorSwatch } from './ColorSwatch';
   
   export default {
     ColorSwatch: <ColorSwatch name="Dark Blue" colorKey="general.darkBlue" />,
   };
   ```

**Comment by hipstersmoothie** [comment]
1.7.4 should fix this. sorry for the regression

**Comment by orther** [comment]
> 1.7.4 should fix this. sorry for the regression

No problem. Thanks for pushing the fix!

I have confirmed it works and solves the problem reported in this issue so closing it.
