### ISSUE TITLE
custom storybook config breaks component level yarn dev

### ISSUE THREAD

**Issue by hainessss** [intuit/design-systems-cli#256]
**Describe the bug**

Perhaps I am just doing something incorrectly but here is what I am experiencing: 

When adding JSX to a custom storybook config (`.storybook/config.js) webpack cannot complete the build when using yarn dev from the individual package level.

**To Reproduce**

Create a new design system with the CLI.

Add a custom decorator to `.storybook/config.js`.  

maybe something like:
```
import React from 'react';
import { configure } from '@storybook/react';
import { makeDecorator } from '@storybook/addons';
import { addDecorator } from '@storybook/react';

// allows styling of your story's container.
const withContainer = makeDecorator({
  name: 'withContainer',
  parameterName: 'container',
  wrapper: (storyFn, context, { parameters }) => {
    return (
      <div {...parameters}>
        {storyFn()}
      </div>
    );
  }
});

addDecorator(withContainer);

configure(
  require.context(
    COMPONENT,
    true,
    /^\.\/((?!node_modules).)*\.stories\.(tsx|ts|js|jsx|mdx)$/
  ),
  module
);
```

create a component.

cd into that component's package.

run yarn dev.

**Expected behavior**

yarn dev should work at both the component and the root level

**Screenshots**

![image](https://user-images.githubusercontent.com/6373177/83291726-a9dd2000-a19d-11ea-8542-e4da3e6db968.png)

Thanks everyone!

**Comment by hipstersmoothie** [comment]
This file is not run though babel so your can use JSX. Try using React.CreateElement instead

**Comment by hipstersmoothie** [comment]
that's odd that it works at the root though? we may be able to improve this then

**Comment by hainessss** [comment]
Ok, good call. createElement works just fine for these purposes. Might be a nice to have tho.

**Comment by hainessss** [comment]
Closing this due to work around above.
