### ISSUE TITLE
storybook not loading on IE with default configuration

### ISSUE THREAD

**Issue by hainessss** [intuit/design-systems-cli#263]
**Describe the bug**

Sorry to post something about IE, but has anyone gotten the storybook to work when developing on IE? The default configuration will error out with:

![image](https://user-images.githubusercontent.com/6373177/83555516-3e5bc100-a4c3-11ea-888e-6523baf0d516.png)

**To Reproduce**

Create a design system with a component and load it in an IE env. (I am using IE 11 on windows 10).

**Expected behavior**

Seems like this should work, is more configuration required?

**Screenshots**

![image](https://user-images.githubusercontent.com/6373177/83555688-85e24d00-a4c3-11ea-89bf-f5891a76f3c8.png)

**Desktop (please complete the following information):**

- OS: windows 10
- Browser IE 11

**Comment by hipstersmoothie** [comment]
Internally we don't support ie11. But I think this just has to do with the default browserslist? Try playing around with that and babel/preset-env should do it's job

**Comment by hainessss** [comment]
The browserlistrc file already accounts for IE 11. Are there any files not getting transpiled?

**Comment by hainessss** [comment]
Ok I got to work in IE by changing the `devtool` webpack option to one of the none eval ones. But also there are two arrow functions in `@proof-ui/storybook/dist/main.js` that break it. If I remove those, everything works fine. What do think the best way to deal with those are @hipstersmoothie ?

**Comment by hipstersmoothie** [comment]
We should probably fix that in proof which is just changing [this setting](https://github.com/intuit/proof/blob/master/tsconfig.build.json#L3) to es5. 

But I think at the root might be wrong. Most of the packages target node so `es2017` makes sense for them. All browser based packages should probably target `es5` (I *think* the storybook plugin is the only browser code, @adierkens?) That setting would be in this file.

**Comment by adierkens** [comment]
Yeah we can change that in proof. The next major version of `proof` gets rid of the storybook plugin dependency all together.

**Comment by adierkens** [comment]
This should work: https://github.com/intuit/proof/pull/46

**Comment by hainessss** [comment]
Awesome, Thank you!!

**Comment by hipstersmoothie** [comment]
To upgrade remove @proof from your lock file and run yarn again. This should install the latest proof

**Comment by hainessss** [comment]
That doesn't seem to be the case? @hipstersmoothie.  Still resolves to 0.0.13 for me.

**Comment by hainessss** [comment]
This was fixed in the 1.10.0 release.
