### ISSUE TITLE
Update Proof plugin to latest version (0.1.1)

### ISSUE THREAD

**Issue by hainessss** [intuit/design-systems-cli#361]
The proof plugin has fallen out of date: currently at 0.0.19.  Facing an issue with proof right now and it is harder to debug against the older version.  The issue may be fixed in the newer version as well.  Could we get this bumped in an upcoming sprint please?

Alternatives:

 Is there a way to separate out the packages?

Thanks!

**Comment by hainessss** [comment]
Did y'all abandon this project 😢

**Comment by hipstersmoothie** [comment]
We have not! Make a or and I'll merge. This might be fixed on next. Most new work has been around the storybook 6.0 release on next

**Comment by hipstersmoothie** [comment]
Have been heads down for a while on a big release we have coming up. Sorry for the late response!

**Comment by hainessss** [comment]
@hipstersmoothie  The migration to version 2 is going smoothly enough (Thank you!). But the Props and JSX add-ons tabs are showing blank.  Any gotchas with those two?

**Comment by hainessss** [comment]
What is the best way to scaffold a system using the next branch? @hipstersmoothie

**Comment by hipstersmoothie** [comment]
I've detailed the required files here https://github.com/intuit/design-systems-cli/pull/270#issue-431353876

Updating the templates now

**Comment by hipstersmoothie** [comment]
Okay you should be able to run `npx  @design-systems/create@2.0.0-next.25` and scaffold a new design system. 

The only really changes to the storybook setup are [here](https://github.com/design-systems-templates/monorepo-template/tree/master/.storybook)

**Comment by hainessss** [comment]
@hipstersmoothie Okay I was able to migrate using that migration guide. The only outstanding issue is that I can't seem to get the docgen plugin to respect the `typings` folder.  Everything I put in there resolves to `any` type.  Do you have any suggestions there? pretty stumped on that.

**Comment by hipstersmoothie** [comment]
Here is a portion of my `.storybook/main.js`

```js
const path = require("path");
const { getMonorepoRoot } = require("@design-systems/cli-utils");

const tsconfigPath = path.resolve(getMonorepoRoot(), "tsconfig.json");

module.exports = {
  presets: [
    "@design-systems/storybook/preset"
  ],
  typescript: {
    reactDocgen: "react-docgen-typescript",
    reactDocgenTypescriptOptions: {
      exclude: ["**/src/icons/**", "**/src/illustrations/**", "**/*.stories.*"],
      shouldRemoveUndefinedFromOptional: true,
      tsconfigPath,
      propFilter(prop) {
        if (prop.parent) {
          return !prop.parent.fileName.includes("@types/react");
        }

        return true;
      },
    },
  },
};
```

Does any of this help? Storybook 6.0 has better defaults for typescript but maybe it's finding the wrong tsconfig

**Comment by hainessss** [comment]
Let me give it a whirl! @hipstersmoothie
