### ISSUE TITLE
ENOENT: no such file or directory, chmod - when trying to npm link

### ISSUE THREAD

**Issue by uriklar** [intuit/design-systems-cli#6]
**Describe the bug**
Getting the following error when trying to `npm link`:
`ENOENT: no such file or directory, chmod '/Users/uriklar/Code/test/bluxome/node_modules/@design-systems/cli/node_modules/@design-systems/core/bin/ds.js'`

**To Reproduce**

I ran `npm init @design-systems`
Created a component using `yarn run create`
from the root folder of the generated folder (generated by the npm init command) i ran `npm link`

**Expected behavior**

npm link succeeds

**Screenshots**

![image](https://user-images.githubusercontent.com/2545447/72418819-41f4e280-3784-11ea-85df-e1b79154a04f.png)

**Desktop (please complete the following information):**

- OS: MacOS Catalina 10.15.2

**Additional context**

Thanks for the awesome looking lib!!

**Comment by OctoD** [comment]
Did you try with yarn? This cli relies on it because of some of it's features.

**Comment by uriklar** [comment]
I didn't. We use npm at my workplace. I'll try with yarn, thanks!

**Comment by hipstersmoothie** [comment]
Yes the CLI uses yarn. That might be the issue. Why are you trying to link from the root? The root is just the monorepo's package.json and wouldn't do much by linking. Instead run `yarn link` from the individual components and packages.

**Comment by uriklar** [comment]
I thought that installing the monorepo would let me import all components. So basically I'll need to consume each package separately

**Comment by hipstersmoothie** [comment]
yup! If you want a package that is all your components in a tree-shakable format I would suggest creating a new package called `components` that you import from.

```sh
yarn create:package --name components
```
