### ISSUE TITLE
ds storybook start - command error

### ISSUE THREAD

**Issue by adierkens** [intuit/design-systems-cli#648]
**Describe the bug**

Errors running `ds storybook start` from a new design-system.

**To Reproduce**

```
npm init @design-systems

cd <repo-name>

yarn storybook
```

**Expected behavior**

The storybook command to start

**Screenshots**

![Screen Shot 2021-04-06 at 1 19 39 PM](https://user-images.githubusercontent.com/13004162/113774220-d1651900-96db-11eb-925a-ddb44122693b.png)

**Comment by gwevans** [comment]
@adierkens Is there a workaround to get storybook up and running?

**Comment by shriuken** [comment]
@gwevans I did this earlier this week, from what I remember I needed to manually install storybook and then update the `.storybook/main.js` to grep correctly for component stories, and deleted all root-level-generated files that storybook created.

Specifically...
1. From the root of your design-cli powered repo, install storybook `npx sb init`
2. Delete auto-generated storybook files that get created at the root of your project except for the `.storybook` folder/files
3. Modify `.storybook/main.js` to look like:
```
module.exports = {
  "stories": [
    "../components/**/*.stories.mdx",
    "../components/**/*.stories.@(js|jsx|ts|tsx)"
  ],
  "addons": [
    "@storybook/addon-links",
    "@storybook/addon-essentials"
  ]
}
```

**Comment by gwevans** [comment]
> @gwevans I did this earlier this week, from what I remember I needed to manually install storybook and then update the `.storybook/main.js` to grep correctly for component stories, and deleted all root-level-generated files that storybook created.

Thanks @shriuken, that worked for me.

**Comment by danilomartinelli** [comment]
Hello, this is not enough, it is necessary to keep the storybook settings made by the CLI. CSS is not persisted for example.

**Comment by danilomartinelli** [comment]
I created a new project after that PR but not work yet

**Comment by yucho** [comment]
@shriuken Can we at least get the patch release for #651 (a.k.a. #652)? The current latest version is broken but this will fix our problem

**Comment by adierkens** [comment]
Should be released in [2.17.3](https://github.com/intuit/design-systems-cli/releases/tag/v2.17.3)

**Comment by danilomartinelli** [comment]
@adierkens I updated today using `ds update` to 2.17.3 but i got the following error when i ran `yarn run dev` (`ds dev`):
<img width="1118" alt="Captura de Tela 2021-05-16 às 12 54 31" src="https://user-images.githubusercontent.com/28323438/118403690-ef605a80-b645-11eb-9c55-c35e784703aa.png">

**Comment by adierkens** [comment]
@danilomartinelli https://github.com/intuit/design-systems-cli/pull/654

**Comment by danilomartinelli** [comment]
Ok, I'm looking forwarding for this PR. Important to create a version of the CI with this fix. Thanks!

**Comment by danilomartinelli** [comment]
@adierkens I updated to `@design-systems/cli": "2.17.4--canary.654.17576.0` and `@design-systems/storybook": "2.17.4--canary.654.17576.0` in Root and now is running smoothly. But styles are not being important.
![Captura de Tela 2021-05-17 às 08 54 40](https://user-images.githubusercontent.com/28323438/118484400-90562080-b6ed-11eb-896a-589f2f6e0526.png)
![Captura de Tela 2021-05-17 às 08 54 45](https://user-images.githubusercontent.com/28323438/118484403-90eeb700-b6ed-11eb-9a40-fca1ff79a544.png)

**Comment by adierkens** [comment]
Can you open a separate issue?
I'm going to close this one out since this is no longer a problem -- but feel free to open new ones as you hit them (and PRs if you can 😄)
