### ISSUE TITLE
Custom config breaks module imports with Storybook 

### ISSUE THREAD

**Issue by ianlapham** [intuit/design-systems-cli#7]
**Describe the bug**

In the storybook section of the docs there are instructions on how to add custom storybook configuration. (https://intuit.github.io/design-systems-cli/#/generated/storybook). 

I am trying to add a custom config file as described in the instructions. I am creating a '.storybook' folder at the root of my ds project and adding 'config.js' (also tried with ts) within that folder. 

When i do this it breaks module imports in my components themselves. If i remove the custom config file the issue goes away. This happens even if the config file is empty. 

Is there additional logic I should be including in the config file? 

**To Reproduce**
 
Create a '.storybook' folder at the root and add a 'config.js' file within it. Try to import a package into a component. 

**Expected behavior**

Expect no issues importing packages within the component.

**Screenshots**

<img width="1794" alt="Screen Shot 2020-01-15 at 1 50 21 PM" src="https://user-images.githubusercontent.com/17100331/72461928-00713100-379e-11ea-8014-68227424ff75.png">

**Desktop (please complete the following information):**

- OS: 10.15
- Browser chrome
- Version  79

**Comment by hipstersmoothie** [comment]
I think your problem is that you aren't loading your stories in you config file.

You need to do something like 

```js
```

**Comment by hipstersmoothie** [comment]
As for the typescript error you should install the types for styled components.

```sh
yarn add -DW @types/styled-components
```

**Comment by hipstersmoothie** [comment]
@ianlapham does this fix your problem?
