### ISSUE TITLE
Test script does not fire the correct exit code during test suite failures

### ISSUE THREAD

**Issue by jsun034** [intuit/design-systems-cli#727]
**Describe the bug**

When running `ds test`, a non-zero exit code is not being fired for all types of test failures. This caused our CICD to release a new version of our package, despite us having failing test suites.

**To Reproduce**

1. Simulate any test suite failure. For example, you can call ds test on an empty test file. 
2a. Run echo $? and see that the exit code is still 0 (success) when it should be 1.
2b. OR, you could run your test in a Jenkins pipeline, and observe how the pipeline passes even though the test results show errors

**Expected behavior**
Jenkins CI should error out for any testing failures.

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by jsun034** [comment]
I raised a PR to fix this issue: https://github.com/intuit/design-systems-cli/pull/726.

**Comment by Amor64** [comment]
@jsun034 can you assign this bug to me to work in Hacktoberfest. Thanks

**Comment by jsun034** [comment]
@Amor64 Hi, I don't have permissions to do it but I'll try and find someone

**Comment by corp-ray** [comment]
this just got fixed in https://github.com/intuit/design-systems-cli/pull/729 . It is in a prerelease version v5.0.0-next.0 .
